# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AGLgis Dialog
                                 A QGIS plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-24
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Caio Arantes
        email                : caiosimplicioarante@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

AGLgis is a graphical interface designed to simplify the use of the 
Sentinel-1 SAR Backscatter Analysis Ready Data Preparation in Google Earth Engine.
This plugin allows users to configure and run Sentinel-1 SAR data processing 
without the need to write code manually.
"""

# =============================================================================
# STANDARD LIBRARY IMPORTS
# =============================================================================
import os
import sys
import re
import json
import array
import tempfile
import datetime
import platform
import subprocess
import traceback
import zipfile
import webbrowser
import io
from functools import partial
from datetime import timedelta

# =============================================================================
# THIRD-PARTY IMPORTS
# =============================================================================
import requests
import pandas as pd
import numpy as np
import geopandas as gpd
import plotly.express as px
import plotly.graph_objects as go
import urllib.request

# Earth Engine imports
from ee_s1_ard import S1ARDImageCollection
import ee

# Additional dependencies
import qgis
# Additional scientific computing imports
import processing
from dateutil.relativedelta import relativedelta
from shapely.geometry import shape
from scipy.signal import savgol_filter
from osgeo import gdal

# =============================================================================
# QGIS IMPORTS
# =============================================================================

# QGIS Core imports
from qgis.core import (
    # Basic QGIS classes
    QgsMessageLog,
    Qgis,
    QgsWkbTypes,
    QgsProject,
    QgsApplication,
    
    # Vector handling
    QgsVectorLayer,
    QgsVectorFileWriter,
    QgsFeatureRequest,
    QgsFeature,
    QgsGeometry,
    QgsField,
    
    # Raster handling
    QgsRasterLayer,
    QgsRasterShader,
    QgsColorRampShader,
    QgsSingleBandPseudoColorRenderer,
    QgsMultiBandColorRenderer,
    QgsContrastEnhancement,
    QgsRasterBandStats,
    
    # Style and visualization
    QgsStyle,
    QgsColorRamp,
    QgsLayerTreeLayer,
    
    # Coordinate systems and geometry
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsRectangle,
    
    # Processing and feedback
    QgsProcessingFeedback,
    
    # Map layers
    QgsMapLayer,
)

# Qt GUI imports
from qgis.PyQt.QtGui import (
    QFont, 
    QColor
)

from qgis.PyQt.QtCore import (
    QDate, 
    Qt, 
    QVariant, 
    QSettings, 
    QTimer, 
    QEvent
)

from qgis.PyQt.QtWidgets import (
    # Application and main window
    QApplication,
    QMainWindow,
    QWidget,
    QDialog,
    
    # Layout managers
    QVBoxLayout,
    QHBoxLayout,
    QGridLayout,
    
    # Input widgets
    QCheckBox,
    QDateEdit,
    QPushButton,
    QToolButton,
    
    # Display widgets
    QLabel,
    QTextBrowser,
    QScrollArea,
    
    # Dialog components
    QMessageBox,
    QFileDialog,
    QDialogButtonBox,
    
    # Size policies
    QSizePolicy,
)

# QGIS PyQt imports
from qgis.PyQt import uic, QtWidgets

# QGIS GUI tools
from qgis.gui import (
    QgsMapToolEmitPoint,
    QgsRubberBand,
    QgsMapToolCapture,
    QgsMapToolExtent,
    QgsMapToolPan,
)

# QGIS utilities
from qgis.utils import iface

# =============================================================================
# LOCAL MODULE IMPORTS
# =============================================================================
from . import (
    map_tools,
    save_utils,
    authentication,
)

# =============================================================================
# UI CONFIGURATION
# =============================================================================

# Load the UI file for the main dialog
language = QSettings().value("locale/userLocale", "en")[0:2]
PLUGIN_DIR = os.path.dirname(os.path.dirname(__file__))

# if language == "pt":
#     ui_file = os.path.join("ui", "aglgis_dialog_base_pt.ui")
# else:

ui_file = os.path.join("ui", "aglgis_dialog_base.ui")
FORM_CLASS, _ = uic.loadUiType(os.path.join(PLUGIN_DIR, ui_file))



# =============================================================================
# MAIN DIALOG CLASS
# =============================================================================

class AGLgisDialog(QDialog, FORM_CLASS):
    """
    Main dialog class for AGLgis plugin.
    
    This class provides a graphical interface for Sentinel-1 SAR Backscatter 
    Analysis Ready Data Preparation using Google Earth Engine. It simplifies
    the process of configuring and running Sentinel-1 SAR data processing
    without requiring manual coding.
    
    Attributes:
        iface: QGIS interface object
        focus_timer: Timer for managing window focus
        Various data processing attributes (aoi, df, collection, etc.)
    """
    
    def __init__(self, parent=None, iface=None):
        """
        Initialize the AGLgis dialog.
        
        Args:
            parent: Parent widget (default: None)
            iface: QGIS interface object (default: None)
        """
        super(AGLgisDialog, self).__init__(parent)
        self.setupUi(self)
        self.iface = iface or qgis.utils.iface
        
        # Configure window properties
        self.setWindowFlags(
            Qt.WindowType.Window |
            Qt.WindowType.WindowCloseButtonHint |
            Qt.WindowType.WindowMinimizeButtonHint |
            Qt.WindowType.WindowMaximizeButtonHint
        )
        self.setModal(False)
        
        # Initialize focus management timer
        self.focus_timer = QTimer()
        self.focus_timer.timeout.connect(self.check_focus)

        # Initialize instance variables
        self.inicialize_variables()

        self.QSlider_horizontalSlider.valueChanged.connect(self.on_slider_value_changed)



        

        if parent is not None:


            self.autentication = bool(getattr(parent, "autentication", False))

            project_id = ""
            try:
                if hasattr(parent, "project_QgsPasswordLineEdit"):
                    project_id = parent.project_QgsPasswordLineEdit.text().strip()
            except Exception:
                project_id = ""

            if not project_id:
                project_id = QSettings().value("MyPlugin/projectID", "", type=str).strip()

            if project_id:
                self.ee_project_id = re.sub(r"[^a-zA-Z0-9_-]", "", project_id)
                print(f"AGLGIS inherited GEE project context: {self.ee_project_id}")

        
        # Setup UI components and signal connections
        self.setup_ui()
        self.connect_signals()

        # Set default values and initial stateo 3 months
        # self.load_intro()
        self.tabWidget.setCurrentIndex(0)

        self.language = QSettings().value("locale/userLocale", "en")[0:2]
        
        # Initialize window size
        QTimer.singleShot(0, lambda: self.resizeEvent("small"))

    # =========================================================================
    # WINDOW EVENT HANDLERS
    # =========================================================================
    
    def on_slider_value_changed(self, value):
        """
        Handle changes to the horizontal slider value.
        
        This method can be used to adjust processing parameters based on
        user input from the slider, allowing for dynamic updates to the
        data processing workflow.
        
        Args:
            value: The new value of the slider
        # """
        # print(f"Slider value changed: {value}")

        self.QLabel_label_slider.setText(f"{value} m")
        # Implement any necessary adjustments based on slider value here

    def showEvent(self, event):
        """
        Handle dialog show event.
        
        Starts the focus timer and ensures proper window sizing.
        
        Args:
            event: The show event object
        """
        super().showEvent(event)
        
        # Ensure window size is locked when first shown
        if not hasattr(self, '_size_locked'):
            self.resizeEvent("small")
            self._size_locked = True

        # Start focus management timer
        if hasattr(self, 'focus_timer'):
            self.focus_timer.start(100)

    def hideEvent(self, event):
        """
        Handle dialog hide event.
        
        Stops the focus timer to prevent unnecessary processing.
        
        Args:
            event: The hide event object
        """
        super().hideEvent(event)
        if hasattr(self, 'focus_timer'):
            try:
                self.focus_timer.stop()
            except RuntimeError:
                # Timer might already be stopped or deleted
                pass

    def check_focus(self):
        """
        Check if the plugin window should be brought to front.
        
        This method implements a less aggressive focus management strategy
        that only raises the window when appropriate, avoiding interference
        with internal QGIS events.
        """
        if not self.isVisible() or self.isMinimized():
            return

        if self.iface is None or not hasattr(self.iface, "mainWindow"):
            return
            
        # Only act when clicking on map canvas specifically
        active_window = QApplication.activeWindow()
        if (active_window == self.iface.mainWindow() and 
            not QApplication.activeModalWidget() and
            not self.isActiveWindow()):
            
            # Only raise window, don't activate to avoid event interference
            self.raise_()

    def closeEvent(self, event):
        """
        Handle dialog close event.
        
        Instead of actually closing the dialog, this method hides it to
        preserve the current state and settings. This allows the user
        to reopen the dialog with all their previous work intact.
        
        Args:
            event: The close event object
        """
        # Stop the focus timer to prevent memory leaks
        if hasattr(self, 'focus_timer'):
            try:
                self.focus_timer.stop()
            except RuntimeError:
                # Timer might already be stopped
                pass
        
        # Hide the dialog instead of closing to preserve state
        self.hide()
        event.ignore()

    def inicialize_variables(self):
        """
        Initialize all instance variables to their default values.
        
        This method sets up all the necessary attributes for data processing,
        UI state management, and Earth Engine operations.
        """
        # Plotting and visualization
        self.plot1 = None
    
        
        # Data processing variables
        self.df = None  # Main dataframe for time series
        self.df_aux = None  # Auxiliary dataframe for filtered data
        self.recorte_datas = None  # Date filtering
        self.selected_dates = []
        self.collection = None  # Earth Engine image collection
        

    def setup_ui(self):
        """
        Perform initial UI component configuration.
        
        This method configures UI elements with appropriate settings,
        permissions, and default values.
        """

        self.QDateEdit_end.setDate(QDate.currentDate())

        print(f"End date set to: {self.QDateEdit_end.date().toString()}")
        print(f"Start date set to: {self.QDateEdit_start.date().toString('yyyy-MM-dd')}")

        self.QDateEdit_start.setDate(QDate.currentDate().addYears(-1))


    def connect_signals(self):
        """
        Connect UI signals to their respective handler methods.
        
        This method establishes all the signal-slot connections for the dialog,
        organizing them by functional areas for better maintainability.
        """
        self.tabWidget.currentChanged.connect(self.on_tab_changed)

        self.load_1index.clicked.connect(self.load_image)
        self.load_1index_preview.clicked.connect(lambda: self.load_image(True))
        self.load_batch.clicked.connect(self.load_batch_clicked)

        self.loadtimeseries.clicked.connect(self.loadtimeseries_clicked)
        self.datasrecorte.clicked.connect(self.datasrecorte_clicked)
        self.salvar.clicked.connect(self.salvar_clicked)

        self.navegador.clicked.connect(self.open_browser)

    def load_batch_clicked (self):

        length = self.dataunica.count()
        print(f"Number of dates in the collection: {length}")
        for i in range(length):
            self.dataunica.setCurrentIndex(i)
            print(f"Loading image for date: {self.dataunica.currentText()}")
            self.load_image(preview=False)  # Load each image in download mode

    # =========================================================================
    # IMAGE LOADING AND PROCESSING
    # =========================================================================


    def apply_buffer(self, aoi):
        """Applies a buffer to the AOI geometry."""
        buffer_distance = self.QSlider_horizontalSlider.value()
        print(f"Applying buffer of {buffer_distance} meters to AOI.")
        if buffer_distance != 0:
            print(f"Buffer distance: {buffer_distance} meters")
            aoi = aoi.map(lambda feature: feature.buffer(buffer_distance))
            #self.aoi = aoi
            return aoi
        else:
            print("No buffer applied")
            return aoi
                    

    def load_image(self, preview=False):
        """
        Load a Sentinel-1 image based on the selected date.
        
        This method downloads and loads a single Sentinel-1 image from the
        processed collection for the selected date, allowing users to visualize
        individual images from their time series.
        
        Args:
            preview (bool): If True, saves to temporary directory. 
                          If False, saves to user-specified output folder.
        """
        print("Loading image...")

        aoi = self.apply_buffer(self.aoi)
        
        # Get selected date and prepare date range
        date = self.dataunica.currentText()
        next_date = (datetime.datetime.strptime(date, "%Y-%m-%d") + 
                    datetime.timedelta(days=1)).strftime("%Y-%m-%d")
        
        # Extract single image from collection
        selected_image = (self.collection
                         .filterDate(date, next_date)
                         .first()
                         .select(['VV', 'VH', 'VVVH_ratio'])
                         .clip(aoi))

        mask = ee.Image(1).clip(aoi).mask()

        # 2. Apply this mask to the final composite image.
        # This operation sets pixels outside the mask to NoData (transparent).
        final_image_masked = selected_image.updateMask(mask)

        # Prepare download URL for the clipped image
        url = final_image_masked.getDownloadURL({
            "scale": 10,
            "region": aoi.geometry().bounds().getInfo(),
            "format": "GeoTIFF",
            "crs": "EPSG:4326",
        })
        
        # Generate unique filename
        base_output_file = f"Sentinel1_{date}.tiff"
        output_file = self.get_unique_filename(base_output_file, temporary=preview)

        # Download the image
        response = requests.get(url)
        if response.status_code == 200:
            with open(output_file, "wb") as f:
                f.write(response.content)
            print(f"Sentinel1 image downloaded as {output_file}")
        else:
            print(f"Failed to download image. HTTP Status: {response.status_code}")
            return

        # Generate unique layer name
        layer_name = f"Sentinel1 {date}"
        base_name = layer_name
        counter = 1
        while QgsProject.instance().mapLayersByName(layer_name):
            layer_name = f"{base_name}_{counter}"
            counter += 1
        print(f"Layer name adjusted to '{layer_name}' to ensure uniqueness.")

        # Load the downloaded image as a raster layer
        raster_layer = QgsRasterLayer(output_file, layer_name, "gdal")
        if not raster_layer.isValid():
            print(f"Failed to load raster layer from {output_file}")
            return
        
        # Configure raster layer properties
        raster_layer.setCrs(QgsCoordinateReferenceSystem("EPSG:4326"))
        QgsProject.instance().addMapLayer(raster_layer)
        print(f"Raster layer '{layer_name}' added to the project.")


    # =========================================================================
    # DATA EXPORT AND SAVING METHODS
    # =========================================================================

    def salvar_clicked(self):
        """
        Handle the save button click event.
        
        This method exports the processed time series data to a CSV file
        using the configured output folder and file naming conventions.
        """
        df = self.df_aux
        name = "Sentinel1_time_series.csv"
        save_utils.save(df, name, self)

    # =========================================================================
    # DATE SELECTION DIALOG METHODS
    # =========================================================================

    def datasrecorte_clicked(self):
        """
        Open a dialog for selecting specific dates for the time series.
        
        This method creates a hierarchical date selection dialog organized
        by years and months, allowing users to filter which dates to include
        in their time series analysis.
        """
        dialog = QDialog(self)
        dialog.setWindowTitle("Date Selection for Time Series")
        dialog.setGeometry(100, 100, 400, 500)

        layout = QVBoxLayout(dialog)

        # Create scrollable area for date checkboxes
        scroll_area = QScrollArea(dialog)
        scroll_area.setWidgetResizable(True)
        scroll_content = QWidget()
        scroll_layout = QVBoxLayout(scroll_content)

        # Initialize checkbox storage containers
        self.checkboxes = []
        self.group_checkboxes = {}  # Month group checkboxes
        self.year_checkboxes = {}   # Year group checkboxes
        self.group_widgets = {}     # Month group content widgets

        # Prepare date data for grouping
        self.df["dates"] = pd.to_datetime(self.df["dates"])
        grouped = self.df.groupby([self.df["dates"].dt.year, self.df["dates"].dt.month])

        # Process each year
        years = self.df["dates"].dt.year.unique()
        for year in sorted(years):
            # Create a year-level widget / Cria um widget de nível de ano
            year_widget = QWidget(dialog)
            year_layout = QVBoxLayout(year_widget)

            # Year-level checkbox (above all content for the year) / Checkbox
            # de nível de ano (acima de todo o conteúdo para o ano)
            year_checkbox = QCheckBox(f"Select All in {year}", dialog)
            year_checkbox.setChecked(
                True
                if self.recorte_datas is None
                else all(
                    str(date.date()) in self.recorte_datas
                    for date in self.df[self.df["dates"].dt.year == year]["dates"]
                )
            )
            year_checkbox.stateChanged.connect(
                lambda state, yr=year: self.toggle_year_checkboxes(yr, state)
            )
            scroll_layout.addWidget(year_checkbox)
            self.year_checkboxes[year] = year_checkbox

            # Indented content for the year / Conteúdo indentado para o ano
            year_content_widget = QWidget(dialog)
            year_content_layout = QVBoxLayout(year_content_widget)
            year_content_layout.setContentsMargins(
                20, 0, 0, 0
            )  # Add indentation for year content
            scroll_layout.addWidget(year_content_widget)

            # Add months under each year / Adiciona meses sob cada ano
            for (group_year, month), group in grouped:
                if group_year != year:
                    continue

                # Create a month-level widget / Cria um widget de nível de mês
                group_label = f"{group_year}-{month:02d}"
                month_widget = QWidget(dialog)
                month_layout = QVBoxLayout(month_widget)

                # Month toggle button / Botão de alternância do mês
                month_toggle_button = QToolButton(dialog)
                month_toggle_button.setText(f"▶ {group_label}")
                month_toggle_button.setCheckable(True)
                month_toggle_button.setChecked(True)
                month_toggle_button.setStyleSheet("text-align: left;")
                month_toggle_button.toggled.connect(
                    lambda checked, grp=month_widget, btn=month_toggle_button, lbl=group_label: self.toggle_group_visibility(
                        grp, btn, lbl
                    )
                )

                # Month-level checkbox / Checkbox de nível de mês
                group_checkbox = QCheckBox(f"Select All in {group_label}", dialog)
                group_checkbox.setChecked(
                    True
                    if self.recorte_datas is None
                    else all(
                        str(date.date()) in self.recorte_datas for date in group["dates"]
                    )
                )
                group_checkbox.stateChanged.connect(
                    lambda state, grp=group_label: self.toggle_group_checkboxes(
                        grp, state
                    )
                )
                month_layout.addWidget(group_checkbox)
                self.group_checkboxes[group_label] = group_checkbox

                # Add individual checkboxes with further indentation / Adiciona
                # checkboxes individuais com mais indentação
                for date in group["dates"]:
                    date_str = str(date.date())
                    checkbox = QCheckBox(date_str, dialog)
                    checkbox.setChecked(
                        True
                        if self.recorte_datas is None
                        else date_str in self.recorte_datas
                    )
                    month_layout.addWidget(checkbox)
                    checkbox.setContentsMargins(
                        20, 0, 0, 0
                    )  # Further indentation for dates
                    self.checkboxes.append((checkbox, group_label, group_year))

                # Add month layout to the year content layout / Adiciona o layout
                # do mês ao layout do conteúdo do ano
                year_content_layout.addWidget(month_toggle_button)
                year_content_layout.addWidget(month_widget)
                self.group_widgets[group_label] = month_widget

        scroll_content.setLayout(scroll_layout)
        scroll_area.setWidget(scroll_content)
        layout.addWidget(scroll_area)

        # Buttons / Botões
        # Use QDialogButtonBox.StandardButton for Qt6 compatibility
        button_box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel, dialog
        )
        button_layout = QHBoxLayout()
        apply_button = QPushButton("Apply", dialog)
        select_button = QPushButton("Select All", dialog)
        deselect_button = QPushButton("Deselect All", dialog)
        button_layout.addWidget(apply_button)
        button_layout.addWidget(select_button)
        button_layout.addWidget(deselect_button)
        layout.addLayout(button_layout)
        layout.addWidget(button_box)

        # Signal Connections / Conexões de Sinal
        button_box.accepted.connect(dialog.accept)
        button_box.rejected.connect(dialog.reject)
        apply_button.clicked.connect(
            self.apply_changes
        )  # Apply without closing / Aplica sem fechar
        select_button.clicked.connect(self.select_all_checkboxes)
        deselect_button.clicked.connect(self.deselect_all_checkboxes)

        if dialog.exec() == QDialog.DialogCode.Accepted:
            self.apply_changes()  # Ensure changes are applied before closing
        else:
            print("Time series dialog canceled. No changes made.")

    def apply_changes(self):
        """
        Apply changes to the selected dates for time series analysis.

        This method updates the selected dates based on the checked checkboxes
        in the date selection dialog and refreshes the time series plot accordingly.
        It does not close the dialog, allowing users to see the immediate effects
        of their selections.
        """
        self.selected_dates = [
            cb.text() for cb, _, _ in self.checkboxes if cb.isChecked()
        ]
        self.recorte_datas = self.selected_dates
        print(f"Selected dates for time series (applied): {self.recorte_datas}")
        
        # Update the auxiliary dataframe and refresh the plot
        self.df_ajust()
        self.plot_timeseries()

    def df_ajust(self):
        """
        Adjust the main DataFrame based on the selected dates.
        
        This method filters the main dataframe to include only the dates
        selected by the user in the date selection dialog. The filtered
        data is stored in df_aux for further processing and visualization.
        """
        df = self.df.copy()
        if self.recorte_datas:
            # Filter dataframe to include only selected dates
            df = df[df["dates"].astype(str).isin([str(d) for d in self.recorte_datas])]
            self.df_aux = df.copy()
        else:
            # If no date filtering, use all data
            self.df_aux = df.copy()

    def toggle_group_visibility(self, group_widget, toggle_button, group_label):
        """
        Toggle the visibility of a month group widget.

        This method shows or hides a month group's content and updates
        the toggle button's appearance accordingly.

        Args:
            group_widget (QWidget): The widget representing the month group
            toggle_button (QToolButton): The button used to toggle visibility
            group_label (str): The label of the group (YYYY-MM format)
        """
        group_widget.setVisible(toggle_button.isChecked())
        toggle_button.setText(
            f"▶ {group_label}" if not toggle_button.isChecked() 
            else f"▼ {group_label}"
        )

    def toggle_group_checkboxes(self, group_label, state):
        """
        Toggle all checkboxes within a specific month group.

        Args:
            group_label (str): The label of the month group (YYYY-MM format)
            state (int): The checkbox state (Qt.Checked or Qt.Unchecked)
        """
        for checkbox, group, _ in self.checkboxes:
            if group == group_label:
                checkbox.setChecked(state == Qt.Checked)

    def toggle_year_checkboxes(self, year, state):
        """
        Toggle all checkboxes within a specific year group.

        This method affects all individual date checkboxes and month group
        checkboxes for the specified year.

        Args:
            year (int): The year to toggle
            state (int): The checkbox state (Qt.Checked or Qt.Unchecked)
        """
        # Toggle individual date checkboxes for the specified year
        for checkbox, _, group_year in self.checkboxes:
            if group_year == year:
                checkbox.setChecked(state == Qt.Checked)
        
        # Toggle month group checkboxes for the specified year
        for group_label, group_checkbox in self.group_checkboxes.items():
            if group_label.startswith(str(year)):
                group_checkbox.setChecked(state == Qt.Checked)

    def select_all_checkboxes(self):
        """Select all checkboxes in the date selection dialog."""
        for checkbox, _, _ in self.checkboxes:
            checkbox.setChecked(True)
        for group_checkbox in self.group_checkboxes.values():
            group_checkbox.setChecked(True)
        for year_checkbox in self.year_checkboxes.values():
            year_checkbox.setChecked(True)

    def deselect_all_checkboxes(self):
        """Deselect all checkboxes in the date selection dialog."""
        for checkbox, _, _ in self.checkboxes:
            checkbox.setChecked(False)
        for group_checkbox in self.group_checkboxes.values():
            group_checkbox.setChecked(False)
        for year_checkbox in self.year_checkboxes.values():
            year_checkbox.setChecked(False)

    # =========================================================================
    # WINDOW POSITIONING AND RESIZING METHODS
    # =========================================================================

    def centralizar(self):
        """
        Center the window on the current screen.

        This method calculates the geometry of the window frame and moves it to
        the center of the available screen space on the current screen without
        changing which screen the dialog is displayed on.
        """
        # Get the current geometry of the window frame
        qtRectangle = self.frameGeometry()
        
        # Determine the center point of the available screen space
        # Uses QApplication.primaryScreen() as replacement for deprecated QDesktopWidget
        screen = QApplication.screenAt(self.frameGeometry().center())
        if screen is None:
            screen = QApplication.primaryScreen()
        centerPoint = screen.availableGeometry().center()
        
        # Move the center of the window frame to the center point of the screen
        qtRectangle.moveCenter(centerPoint)
        # Move the window to the new position
        self.move(qtRectangle.topLeft())

    def resizeEvent(self, size):
        """
        Handle window resize events with predefined size configurations.
        
        This method manages two window size modes: "small" for basic operations
        and "big" for data visualization and analysis. It locks the window
        size to prevent manual resizing.
        
        Args:
            size (str): Either "small" or "big" to set the window size
        """
        # Remove any existing size constraints
        self.setMinimumSize(0, 0)
        self.setMaximumSize(16777215, 16777215)

        if size == "small":
            # Small window for basic operations (tabs 0-4)
            self.resize(765, 371)
            self.setFixedSize(self.width(), self.height())
        elif size == "big":
            # Large window for data visualization (tabs 5+)
            self.resize(1145, 620)
            self.setFixedSize(self.width(), self.height())

    # =========================================================================
    # TAB NAVIGATION AND CONTROL METHODS
    # =========================================================================

    def on_tab_changed(self, index):
        """
        Handle tab change events with comprehensive validation and setup.
        
        This method manages tab transitions, enforces step-by-step workflow,
        handles authentication checks, and performs tab-specific initialization.
        
        Args:
            index (int): The index of the newly selected tab
        """
        # Prevent recursion during programmatic tab changes
        if getattr(self, '_programmatic_tab_change', False):
            return

        def _safe_set_current_index(target_index):
            """Safely change tab index without triggering recursive events."""
            if not hasattr(self, 'tabWidget'):
                return False

            if self.tabWidget.currentIndex() != target_index:
                self._programmatic_tab_change = True
                try:
                    self.tabWidget.setCurrentIndex(target_index)
                finally:
                    self._programmatic_tab_change = False
                return True
            return False

        # Authentication check - must be authenticated to access tabs beyond 0
        # if not getattr(self, 'autentication', False) and index != 0:
        #     QMessageBox.warning(self, "Access Denied", "Please authenticate first!")
        #     _safe_set_current_index(0)
        #     return

        # Handle window resizing based on tab
        if index < 1:
            self.resizeEvent("small")
        else:
            self.resizeEvent("big")
            # Center window only once for large tabs
            if not getattr(self, '_centralized', False):
                self.centralizar()
                self._centralized = True

        return

    # =========================================================================
    # NAVIGATION BUTTON METHODS
    # =========================================================================

    # =========================================================================
    # FILE AND FOLDER MANAGEMENT METHODS
    # =========================================================================


    def pop_warning(self, message):
        """
        Display a warning dialog with the specified message.
        
        Args:
            message (str): The warning message to display
        """
        QApplication.restoreOverrideCursor()
        msg = QMessageBox(self)
        msg.setWindowTitle("Warning!")
        msg.setIcon(QMessageBox.Icon.Warning)
        msg.setText(message)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok)
        msg.button(QMessageBox.StandardButton.Ok).setText("OK")
        msg.setStyleSheet("font-size: 10pt;")
        msg.exec()

    # =========================================================================
    # VECTOR LAYER MANAGEMENT METHODS
    # =========================================================================

    def get_subdirectory_filename(self, base_name, temporary=False):
        """
        Create a unique layer name with incrementing number and matching subdirectory.
        
        Args:
            base_name (str): Base name for the layer and directory
            temporary (bool): If True, use temporary directory instead of output folder
            
        Returns:
            str: Path to the unique filename
        """
        if temporary:
            base_output_folder = tempfile.gettempdir()
        else:
            parent = self.parent()
            base_output_folder = getattr(parent, "output_folder", None)
        
        # Find a unique layer name with incrementing number
        counter = 1
        layer_name = f"{base_name}{counter}"
        subdirectory_path = os.path.join(base_output_folder, layer_name)
        
        # Keep incrementing until we find an unused name
        while os.path.exists(subdirectory_path):
            counter += 1
            layer_name = f"{base_name}{counter}"
            subdirectory_path = os.path.join(base_output_folder, layer_name)
        
        # Create the directory if it doesn't exist
        while os.path.exists(subdirectory_path):
            counter += 1
            layer_name = f"{base_name}{counter}"
            subdirectory_path = os.path.join(base_output_folder, layer_name)
        
        os.makedirs(subdirectory_path)
        
        # Create the filename with the same base name
        file_name = f"{layer_name}.shp"
        file_path = os.path.join(subdirectory_path, file_name)
        
        print(f"Unique layer name: {layer_name}")
        print(f"Unique filename: {file_path}")
        
        return file_path, layer_name

    def get_unique_filename(self, base_file_name, temporary=False):
        """
        Generate a unique filename by appending a counter if the file already exists.
        
        Args:
            base_file_name (str): The base filename to make unique
            temporary (bool): If True, use temporary directory instead of output folder
            
        Returns:
            str: Path to a unique filename
        """
        name, extension = os.path.splitext(base_file_name)

        parent = self.parent()
        self.output_folder = getattr(parent, "output_folder", None)
        
        if temporary:
            output_folder = tempfile.gettempdir()
            output_file = os.path.join(output_folder, base_file_name)
        else:
            output_folder = self.output_folder
            output_file = os.path.join(output_folder, base_file_name)
            
        counter = 1
        while os.path.exists(output_file):
            output_file = os.path.join(
                output_folder, f"{name}_{counter}{extension}"
            )
            counter += 1

        print(f"Unique filename: {output_file}")
        return output_file

    def resetting(self):
        """
        Reset processing variables to their initial state.
        
        This method clears previously processed data and reloads the AOI
        to prepare for a new analysis run.
        """
        self.recorte_datas = None
        self.df = None
        self.collection = None
        self.fig = None
        self.df_aux = None

    # =========================================================================
    # TIME SERIES PROCESSING METHODS
    # =========================================================================

    def loadtimeseries_clicked(self):
        """
        Handle the load time series button click event.
        
        This method initiates the complete time series processing workflow,
        including Earth Engine data processing, date loading, and visualization.
        """
        try:
            QApplication.setOverrideCursor(Qt.CursorShape.WaitCursor)
            self.resetting()
            self.collection = self.ee_process()
            self.load_dates()
            self.plot_timeseries()
            self.next_clicked()
        except Exception as e:
            print(f"Error during timeseries loading: {e}")
            self.pop_warning(f"Error loading time series: {str(e)}")
        finally:
            QApplication.restoreOverrideCursor()

    def ee_process(self):

        #self.cheching()
        """
        Process Earth Engine data to create a time series collection.
        
        This method configures and executes the Sentinel-1 ARD processing
        based on user-selected parameters and returns the processed collection.
        
        Returns:
            ee.ImageCollection: Processed Sentinel-1 image collection with time series data
        """
        # Determine orbit direction from user selection
        orbit = self.QComboBox_orbit.currentText() != "DESCENDING"

        # Configure the S1ARD processor with user parameters

        # Inherit AOI directly from parent dialog on initialization
        self.aoi = getattr(self.parent(), "aoi", None)

        processor = S1ARDImageCollection(
            geometry=self.aoi,
            start_date=self.QDateEdit_start.date().toString('yyyy-MM-dd'),
            stop_date=self.QDateEdit_end.date().toString('yyyy-MM-dd'),
            polarization=self.QComboBox_polarization.currentText(),
            apply_border_noise_correction=self.QCheckBox_apply_border_noise_correction.isChecked(),
            apply_terrain_flattening=self.QCheckBox_apply_terrain_flattening.isChecked(),
            apply_speckle_filtering=self.QCheckBox_apply_speckle_filtering.isChecked(),
            output_format=self.QComboBox_output.currentText(),
            ascending=orbit  # False for descending orbit, True for ascending orbit
        )

        collection = processor.get_collection().sort('system:time_start')

        size = collection.size().getInfo()
        print(f"Number of images in collection: {size}")

        if size == 0:
            self.pop_warning("No images found for the selected criteria.")
            return None

        # Add VV/VH ratio band to each image
        def add_vvvh_ratio_band(image):
            ratio = image.select("VV").divide(image.select("VH")).rename("VVVH_ratio")
            return image.addBands(ratio)

        # Map the function to add the VV/VH ratio band
        try:
            collection = collection.map(add_vvvh_ratio_band)
        except Exception as e:
            print(f"Error adding VV/VH ratio band: {e}")
            self.pop_warning(f"Error processing images: {str(e)}")
            return None

        # Extract the VVVH_ratio band and calculate mean values for each image
        def get_vvvh_ratio_mean(image):
            stats = image.select("VVVH_ratio").reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=self.aoi,
                scale=10,
                maxPixels=1e9
            )
            # Get image date
            date = image.date().format('YYYY-MM-dd')
            return ee.Feature(None, {
                'date': date,
                'VVVH_ratio_mean': stats.get('VVVH_ratio')
            })

        # Map the function over the collection and get the results
        vvvh_ratio_ts = collection.map(get_vvvh_ratio_mean).getInfo()

        # Extract data for DataFrame creation
        data = [
            {'dates': f['properties']['date'], 'AOI_average': f['properties']['VVVH_ratio_mean']}
            for f in vvvh_ratio_ts['features']
        ]

        # Create and store DataFrames
        df = pd.DataFrame(data)
        #print(df)
        self.df = df.copy()
        self.df_aux = df.copy()

        return collection

    def df_adjust(self):
        """
        Adjust the main DataFrame based on selected dates.
        
        This method filters the DataFrame to include only the dates
        that have been selected by the user for analysis.
        """
        df = self.df.copy()
        if self.recorte_datas:
            # Filter DataFrame to include only selected dates
            df = df[df["dates"].astype(str).isin([str(d) for d in self.recorte_datas])]
            self.df_aux = df.copy()
        else:
            self.df_aux = df.copy()

    # =========================================================================
    # VISUALIZATION AND PLOTTING METHODS
    # =========================================================================

    def plot_timeseries(self):
        """
        Plot the time series data using Plotly.
        
        This method creates an interactive time series plot with customized
        configuration and styling for the VV/VH ratio data.
        """
        # Configure Plotly display options
        self.config = {
            "displaylogo": False,
            "modeBarButtonsToRemove": [
                "toImage",
                "sendDataToCloud",
                "zoom2d",
                "pan2d",
                "select2d",
                "lasso2d",
                "zoomIn2d",
                "zoomOut2d",
                "autoScale2d",
                "resetScale2d",
                "hoverClosestCartesian",
                "hoverCompareCartesian",
                "zoom3d",
                "pan3d",
                "orbitRotation",
                "tableRotation",
                "resetCameraLastSave",
                "resetCameraDefault3d",
                "hoverClosest3d",
                "zoomInGeo",
                "zoomOutGeo",
                "resetGeo",
                "hoverClosestGeo",
                "hoverClosestGl2d",
                "hoverClosestPie",
                "toggleHover",
                "toggleSpikelines",
                "resetViews",
            ],
        }

        # Create the time series plot
        self.fig = px.line(
            self.df_aux, 
            x='dates', 
            y='AOI_average', 
            markers=True, 
            title='VV/VH Time Series'
        )
        self.fig.update_layout(
            xaxis_title='Date', 
            yaxis_title='VV/VH Ratio'
        )

        # Render the plot in the web view
        self.QWebView.setHtml(
            self.fig.to_html(include_plotlyjs="cdn", config=self.config)
        )

    def open_browser(self):
        """
        Open the time series plot in the default web browser.
        
        This method exports the current plot to an HTML file and opens it
        in the system's default web browser for better viewing.
        """
        if self.fig:
            temp_file = tempfile.NamedTemporaryFile(
                mode='w', suffix='.html', delete=False
            )
            temp_file.write(
                self.fig.to_html(include_plotlyjs="cdn", config=self.config)
            )
            temp_file.close()
            
            # Open in default browser
            webbrowser.open('file://' + temp_file.name)
        else:
            self.pop_warning("No plot available to open in browser.")

    def load_dates(self):
        """
        Load and populate the date selection interface.
        
        This method extracts unique dates from the processed DataFrame
        and populates the date selection widgets for user interaction.
        """
        if self.df is not None and not self.df.empty:
            # Get unique dates and sort them
            dates = self.df['dates'].unique().astype(str).tolist()
            self.available_dates = sorted(dates)
            
            # Populate the date selection combo box
            self.dataunica.clear()
            self.dataunica.addItems(dates)
            # Set to the most recent date by default
            self.dataunica.setCurrentIndex(self.dataunica.count() - 1)
            
            print(f"Available dates loaded: {len(self.available_dates)} dates")
        else:
            print("No data available for date loading")
            self.available_dates = []

    def next_clicked(self):
        """Navigate to the next tab in the tab widget."""
        current_index = self.tabWidget.currentIndex()
        next_index = (current_index + 1) % self.tabWidget.count()
        self.tabWidget.setCurrentIndex(next_index)


class AglgisDialog(AGLgisDialog):
    pass
